const data = [
  {
    Url: "http://google.com",
    Title: "home _",
    Color: "#fff",
    Hover: "primary.orange",
    Key: "#aas",
  },
  {
    Url: "http://facebook.com",
    Title: "project _",
    Color: "#fff",
    Hover: "primary.orange",
    Key: "#aas12",
  },
  {
    Url: "http://facebook.com",
    Title: "contact me _",
    Color: "#fff",
    Hover: "primary.orange",
    Key: "#aas23",
  },
];

export default data;
